"""Build the bilingual, section-level index from the six published HTML guides.

No network or third-party dependencies. Default checks freshness; --patch emits
an apply_patch patch. Includes collapsed content, excludes navigation and copy
instructions. Only published page text enters the index, not private repo files.
"""
import json
import sys
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAGES = [
    'product-research/product-research',
    'product-ux-rethinking/product-framing',
    'product-ux-rethinking/ux-rethinking',
    'testing-evaluation-system/testing-evaluation-system',
    'product-analytics-experimentation/product-analytics-experimentation',
    'delivery-learning/delivery-learning',
]
VOID = {'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'link', 'meta', 'param', 'source', 'track', 'wbr'}


class Node:
    def __init__(self, tag='', attrs=()):
        self.tag, self.attrs, self.children = tag, dict(attrs), []

    def nodes(self):
        yield self
        for child in self.children:
            if isinstance(child, Node):
                yield from child.nodes()

    def text(self, lang):
        if self.tag in {'script', 'style', 'svg'} or 'quick-start' in self.attrs.get('class', '').split():
            return ''
        if 'data-' + lang in self.attrs:
            return self.attrs['data-' + lang]
        return ' '.join(c.text(lang) if isinstance(c, Node) else c for c in self.children)


class Tree(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.root = Node()
        self.stack = [self.root]

    def handle_starttag(self, tag, attrs):
        node = Node(tag, attrs)
        self.stack[-1].children.append(node)
        if tag not in VOID:
            self.stack.append(node)

    def handle_endtag(self, tag):
        for i in range(len(self.stack) - 1, 0, -1):
            if self.stack[i].tag == tag:
                self.stack = self.stack[:i]
                break

    def handle_data(self, data):
        self.stack[-1].children.append(data)


def clean(text):
    return ' '.join(text.split())


records = []
for page in PAGES:
    tree = Tree()
    tree.feed((ROOT / 'prompts' / (page + '.html')).read_text())
    body = next(n for n in tree.root.nodes() if n.tag == 'body')
    main = next(n for n in body.nodes() if n.tag == 'main')
    for section in (n for n in main.children if isinstance(n, Node) and n.tag == 'section'):
        heading = next((n for n in section.nodes() if n.tag in {'h1', 'h2'}), None)
        if heading is None:
            raise ValueError('Missing section heading: ' + page)
        anchor = section.attrs.get('id') or 'start'
        records.append({
            'path': page + '.html', 'anchor': anchor,
            'page': {lang: body.attrs['data-page-title-' + lang] for lang in ['en', 'zh']},
            'title': {lang: clean(heading.text(lang)) for lang in ['en', 'zh']},
            'text': {lang: clean(section.text(lang)) for lang in ['en', 'zh']},
        })

target = ROOT / 'prompts/_shared/search-index.js'
after = '// Generated by scripts/build-search-index.py; do not edit by hand.\nwindow.PPL_SEARCH_INDEX = ' + json.dumps(records, ensure_ascii=False, separators=(',', ':')) + ';\n'
before = target.read_text() if target.exists() else None
if '--patch' in sys.argv:
    if before != after:
        print('*** Begin Patch')
        print(('*** Update File: ' if before is not None else '*** Add File: ') + str(target))
        if before is not None:
            print('@@')
            for line in before.splitlines():
                print('-' + line)
        for line in after.splitlines():
            print('+' + line)
        print('*** End Patch')
else:
    print(('PASS' if before == after else 'STALE') + f': bilingual search index, {len(PAGES)} pages / {len(records)} sections.')
    sys.exit(0 if before == after else 1)
